### PR TITLE
Base URL change

### PR DESCRIPTION
**Pull request by kobleistvan**
Fitbit changed their base url for oauth2 work, so I did the same in the conf file

### CODE REVIEW

**Comment by guumaster** [comment]
well, this is odd. They've changed only the authorization url, and not the token. Does it work for you with only this change? I can't fetch new tokens now.

**Comment by kobleistvan** [comment]
Yah, realized afterwards. I need to work also with withings' API atm, which has oAuth1, so I fell back to use oAuth1 for fitbit too, for now at least, while it's still in beta

**Comment by kobleistvan** [comment]
Hi again. Just realized I need oAuth2 on fitbit for heartrate data... any luck fixing the broken urls?

**Comment by kobleistvan** [comment]
OAuth 2.0: Authorization URI
https://www.fitbit.com/oauth2/authorize
OAuth 2.0: Access/Refresh Token Request URI
https://api.fitbit.com/oauth2/token

**Comment by guumaster** [comment]
Yes, that is the problem, Simple oAuth client only take one base URL. And even using two different clients, I can't get a token from an auth code

**Comment by guumaster** [comment]
I've updated the urls and needed two different objects because of the different base url. I'm closing this. Check [this commit](https://github.com/thegameofcode/fitbit-client-oauth2/commit/deabd5ffbfb1114f47d820815528ef7e006a695e)

**Comment by kobleistvan** [comment]
Thank you very much :)
Good job!

**Comment by guumaster** [comment]
You're welcome. It's on npm too.

**Pull request closed without merging**
